kind: pipeline
type: kubernetes
name: eskwelabs-web

steps:
  - name: ecr-publish
    image: plugins/ecr
    environment:
      NODE_ENV: production
    settings:
      create_repository: true
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_ACCESS_SECRET_KEY
      repo: eskwelabs-web
      registry: 839343020172.dkr.ecr.ap-southeast-1.amazonaws.com
      region: ap-southeast-1
      tags: [latest, 7608eee6-cd43-4fc4-bc49-4188d65de0e3]
      privileged: true
  - name: deploy
    image: tuttinator/kubectl
    commands:
      - kubectl apply -f eks/deployment.yaml
    trigger:
      branch:
        - develop
  - name: deploy-prod
    image: tuttinator/kubectl
    commands:
      - kubectl apply -f eks/production.yaml
    trigger:
      branch:
        - main
